# Generated by Django 5.1.2 on 2024-10-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_remove_systemuser_email_remove_systemuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_by',
            field=models.CharField(max_length=20),
        ),
    ]
